url: https://www.churchincanberra.org
baseurl: ""
permalink: pretty
title: "Church in Canberra"
tagline: "We welcome all believers who have faith in Jesus Christ."
description: "We are located in Canberra, the capital city of Australia."

home:
  limit_services: 6

collections:
  about:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "about"
    values:
      layout: "service"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
