url: https://www.churchincanberra.org
baseurl: ""
permalink: pretty
title: "Church in Canberra"
tagline: "We welcome all believers who have faith in Jesus Christ."
description: "We are located in Canberra, the capital city of Australia."

home:
  limit_services: 6

collections:
  about:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "about"
    values:
      layout: "service"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

contact_api: https://prod-29.australiaeast.logic.azure.com:443/workflows/d7adb9d6792b4fa7a435f9a09ff29efe/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uo2IvombHEnZG7fo32SHP0-xtvty1pjfvOYsbWZV4vs
