# Description: This workflow updates the content in the announcement.md file.
# It follows the following steps:
# 1. Calls the Mailchimp archive URL to retrieve the latest campaign URL.
# 2. Retrieves the content from the campaign URL.
# 3. Filters the content and updates the announcement.md file.
# 4. Commits the updated announcement.md file to the repository.

name: Announcement

on:
  workflow_dispatch:

  schedule:
    - cron: '30 23 * * 6' # This runs at 9:30 AM Australia/Sydney time (UTC+10) every Sunday
    - cron: '30 22 * * 6' # This runs at 9:30 AM Australia/Sydney time (UTC+11) every Sunday during daylight saving

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ANNOUNCEMENTBOT_APP_ID }}
          private-key: ${{ secrets.ANNOUNCEMENTBOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: |
          npm install jsdom
          npm install node-fetch
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Get latest announcement
        run: |
          node .github/scripts/getAnnouncement.mjs
        shell: bash

      - name: Upload announcement
        uses: actions/upload-artifact@v4
        with:
          name: draft-copy
          path: ./e4b1ffcb4ee645488a4729bd77e0b3d89bc0a70d/announcements.md

      - name: Commit announcement updates
        run: |
          BRANCH_NAME="announcement/$(date +'%Y%m%d')"
          COMMIT_MSG="Announcement updates on $(date +'%Y-%m-%d')"

          git config --global user.email "announcement-bot@users.noreply.github.com "
          git config --global user.name "announcement-bot"
          git checkout -b $BRANCH_NAME
          git add ./e4b1ffcb4ee645488a4729bd77e0b3d89bc0a70d/announcements.md
          git commit -m "$COMMIT_MSG"
          git push origin $BRANCH_NAME

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ steps.app-token.outputs.token }}" > token.txt
          gh auth login --with-token < token.txt
          rm token.txt
        shell: bash

      - name: Create Pull Request
        id: create_pr
        run: |
          PR_TITLE="Announcement updates on $(date +'%Y-%m-%d')"
          PR_BODY="Automated PR for announcement updates"
          PR_URL=$(gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME --repo ${{ github.repository }})
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        shell: bash

      - name: Merge Pull Request
        run: |
          COMMIT_MSG=$(gh pr view $PR_URL --json title -q ".title")
          gh pr merge $PR_URL --auto --squash --delete-branch --subject "$COMMIT_MSG [skip ci]"
        shell: bash
