# Description: This workflow updates the content in the announcement.md file.
# It follows the following steps:
# 1. Calls the Mailchimp archive URL to retrieve the latest campaign URL.
# 2. Retrieves the content from the campaign URL.
# 3. Filters the content and updates the announcement.md file.
# 4. Commits the updated announcement.md file to the repository.

name: Draft announcement

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:

  schedule:
    - cron: '0 20 * * 1-6' # This runs at 6:00 AM Australia/Sydney time (UTC+10) every Monday to Saturday
    - cron: '30 23 * * 6' # This runs at 9:30 AM Australia/Sydney time (UTC+10) every Sunday
    - cron: '30 22 * * 6' # This runs at 9:30 AM Australia/Sydney time (UTC+11) every Sunday during daylight saving

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.ANNOUNCEMENTBOT_APP_ID }}
          private-key: ${{ secrets.ANNOUNCEMENTBOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: |
          npm install jsdom
          npm install node-fetch
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Get latest announcement
        run: |
          node .github/scripts/getAnnouncement.mjs
        shell: bash

      - name: Upload announcement
        uses: actions/upload-artifact@v4
        with:
          name: draft-copy
          path: ./e4b1ffcb4ee645488a4729bd77e0b3d89bc0a70d/announcements.md

      - name: Commit announcement updates
        run: |
          COMMIT_MSG="Announcement updates on $(date +'%Y-%m-%d')"

          git config --global user.email "churchincanberra@users.noreply.github.com "
          git config --global user.name "churchincanberra"
          git add ./e4b1ffcb4ee645488a4729bd77e0b3d89bc0a70d/announcements.md

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "$COMMIT_MSG"
            git push 
          fi
        shell: bash
